### ISSUE TITLE
Minecraft Authentication Error An internal server error occured

### ISSUE THREAD

**Issue by Ma323fe** [MinecraftAuthentication/status#58]
im getting this error when i try to link my  patreon
<img width="685" alt="Screenshot 2023-11-19 at 12 02 00 pm" src="https://github.com/MinecraftAuthentication/status/assets/147388198/e06ea5e9-92f3-44f2-985b-e134f9353e96">
I first click the connect button
<img width="642" alt="Screenshot 2023-11-19 at 12 30 37 pm" src="https://github.com/MinecraftAuthentication/status/assets/147388198/1ddc89c0-c567-4634-888c-d070d4d9fbd5">
then the allow button
<img width="517" alt="Screenshot 2023-11-19 at 12 30 21 pm" src="https://github.com/MinecraftAuthentication/status/assets/147388198/d9efb62a-4ab4-44ce-9042-b632f13ae648">
and then this shows up
<img width="685" alt="Screenshot 2023-11-19 at 12 02 00 pm" src="https://github.com/MinecraftAuthentication/status/assets/147388198/ea240656-b1be-47f5-8967-a083e20d908b">

**Comment by Scarsz** [comment]
Has since been fixed
